name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Verify and tidy dependencies
        run: |
            go mod tidy
            go mod verify
        

      - name: Run tests
        run: go test -v ./...

      - name: Build application
        run: go build -v -o health-api

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/health-app:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Deploy to Server (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/health-app:latest
            docker stop health-api || true
            docker rm health-api || true
            docker run -d --name health-api --restart unless-stopped -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/health-app:latest

      - name: Verify deployment
        run: |
          curl --fail http://${{ secrets.VM_HOST }}:8080/health
